### ISSUE TITLE
Forking fibers?

### ISSUE THREAD

**Issue by cristipp** [saghul/python-fibers#18]
I'm interested in lightweight forking of fibers, with the intent of implementing reentrant coroutines, aka continuations, aka call/cc. Best attempt so far:

```
import copy
import fibers

def test_fork():
    def fn1():
        print("fn1")
        x = f2.switch(fibers.current())
        print("fn1", x)
        f2.switch(x)

    def fn2():
        crt = f1.switch()
        # TypeError: cannot serialize 'fibers._cfibers.Fiber' object
        # crt2 = copy.deepcopy(crt)
        a = crt.switch('a')
        print('result' , a)
        # b = crt2.switch('b')
        # print('result', b)

    f1 = fibers.Fiber(fn1)
    f2 = fibers.Fiber(fn2)
    f2.switch()
```

Is this doable?

**Comment by saghul** [comment]
Nope, you cannot duplicate a Fiber. I'm not even sure it's possible :-S

**Comment by cristipp** [comment]
Alas, that's likely true. I've read through stacklet code and found `/* stacklet_handle _stacklet_switch_to_copy(stacklet_handle) --- later */`. Was never implemented. Given that stacklets are called "one shot continuations", seems unlikely to happen.
